name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push]

jobs:
  Build-multiplatform:
    runs-on: [ubuntu-latest]

    steps:

    - name: Evaluate Build Environment variables
      run: |
        echo $(basename ${{github.repository}}) | sed -E 's/.*/IMAGENAME=\L&/' | tee -a $GITHUB_ENV

    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download the act_runner
      shell: bash
      run: |
        curl -sLo runner_arm64 ${{vars.RUNNER_ARM64}} && chmod +x runner_arm64
        curl -sLo runner_amd64 ${{vars.RUNNER_AMD64}} && chmod +x runner_amd64

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGENAME}}